package source;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frmQLSV extends javax.swing.JFrame {
    private QuanLyDiemSinhVienPanel StudentPanel;
    private QuanLySinhVienPanel QLSV;
    
    /** Creates new form frmQLSV */
    public frmQLSV() {
        initComponents();
        this.setLocationRelativeTo(null);
        
      //  setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnQuanLySinhVien = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnQuanLyDiem = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnGioiThieu = new javax.swing.JButton();
        TabbedPaneQLSV = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_DangXuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnu_Thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_QLSV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnu_QuanLyDiem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGioiThieu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-32.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);
        jToolBar1.add(jSeparator4);

        btnQuanLySinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btnQuanLySinhVien.setText("Quản lý Sinh Viên");
        btnQuanLySinhVien.setFocusable(false);
        btnQuanLySinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLySinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySinhVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuanLySinhVien);
        jToolBar1.add(jSeparator5);

        btnQuanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gpa-icon-32.png"))); // NOI18N
        btnQuanLyDiem.setText("Quản lý điểm");
        btnQuanLyDiem.setFocusable(false);
        btnQuanLyDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuanLyDiem);
        jToolBar1.add(jSeparator6);

        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-help-about-icon-32.png"))); // NOI18N
        btnGioiThieu.setText("Giới thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        jMenu1.setText("Hệ thống");

        mnu_DangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-16.png"))); // NOI18N
        mnu_DangXuat.setText("Đăng xuất");
        mnu_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_DangXuat);
        jMenu1.add(jSeparator3);

        mnu_Thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnu_Thoat.setText("Thoát");
        mnu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_ThoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_Thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mnu_QLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        mnu_QLSV.setText("Quản lý sinh viên");
        mnu_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QLSVActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QLSV);
        jMenu2.add(jSeparator2);

        mnu_QuanLyDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-document-edit-icon-16.png"))); // NOI18N
        mnu_QuanLyDiem.setText("Quản lý điểm");
        mnu_QuanLyDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QuanLyDiemActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_QuanLyDiem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");
        jMenu3.add(jSeparator1);

        menuGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Help-icon-16.png"))); // NOI18N
        menuGioiThieu.setText("Giới thiệu");
        menuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(menuGioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneQLSV, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabbedPaneQLSV, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySinhVienActionPerformed
        if (QLSV == null) {
            QLSV = new QuanLySinhVienPanel();
            TabbedPaneQLSV.addTab("Quản lý Sinh Viên", QLSV);
        }
        TabbedPaneQLSV.setSelectedComponent( QLSV);
    }//GEN-LAST:event_btnQuanLySinhVienActionPerformed

    private void mnu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_ThoatActionPerformed
            System.exit(0);
    }//GEN-LAST:event_mnu_ThoatActionPerformed

    private void mnu_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QLSVActionPerformed
        btnQuanLySinhVienActionPerformed(evt);
    }//GEN-LAST:event_mnu_QLSVActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        frGioiThieu frame = new frGioiThieu();
        frame.setLocationRelativeTo(null);
        frame.show();
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void menuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGioiThieuActionPerformed
        btnGioiThieuActionPerformed(evt);
    }//GEN-LAST:event_menuGioiThieuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        frDangNhap dagnhap = new frDangNhap();
        dagnhap.setVisible(true);
        dagnhap.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mnu_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DangXuatActionPerformed
        // TODO add your handling code here:
        btnDangXuatActionPerformed(evt);
    }//GEN-LAST:event_mnu_DangXuatActionPerformed

    private void mnu_QuanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QuanLyDiemActionPerformed
        // TODO add your handling code here:
           if (StudentPanel == null) {
            StudentPanel = new QuanLyDiemSinhVienPanel();
            //ImageIcon icon = new ImageIcon(getClass().getResource("image/10207-man-student-light-skin-tone-icon-16.png"));
            // Tao 1 tabbedPane chua 1 jframe, jframe duoc add vao tabbedpane co ten Quan ly sinh vien
            TabbedPaneQLSV.addTab("Quản lý điểm sinh viên",  StudentPanel);
            
        }
        TabbedPaneQLSV.setSelectedComponent(StudentPanel);
    }//GEN-LAST:event_mnu_QuanLyDiemActionPerformed

    private void btnQuanLyDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDiemActionPerformed
        
           if (StudentPanel == null) {
            StudentPanel = new QuanLyDiemSinhVienPanel();
            //ImageIcon icon = new ImageIcon(getClass().getResource("image/10207-man-student-light-skin-tone-icon-16.png"));
            // Tao 1 tabbedPane chua 1 jframe, jframe duoc add vao tabbedpane co ten Quan ly sinh vien
            TabbedPaneQLSV.addTab("Quản lý điểm sinh viên",  StudentPanel);
            
        }
        TabbedPaneQLSV.setSelectedComponent(StudentPanel);
    }//GEN-LAST:event_btnQuanLyDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneQLSV;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnQuanLyDiem;
    private javax.swing.JButton btnQuanLySinhVien;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuGioiThieu;
    private javax.swing.JMenuItem mnu_DangXuat;
    private javax.swing.JMenuItem mnu_QLSV;
    private javax.swing.JMenuItem mnu_QuanLyDiem;
    private javax.swing.JMenuItem mnu_Thoat;
    // End of variables declaration//GEN-END:variables
}
